PRAGMA foreign_keys = ON;

CREATE TABLE hoa_phases (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'planned', 'inactive')),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE properties (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  phase_id INTEGER NOT NULL REFERENCES hoa_phases(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  street_number INTEGER NOT NULL CHECK (street_number > 0),
  street_name TEXT NOT NULL,
  street_suffix TEXT NOT NULL,
  city TEXT NOT NULL DEFAULT 'Lindale',
  state TEXT NOT NULL DEFAULT 'TX',
  postal_code TEXT NOT NULL DEFAULT '75771',
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'planned', 'inactive')),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (street_number, street_name, street_suffix, city, state, postal_code)
);

CREATE INDEX properties_registration_list_idx
  ON properties(status, street_name, street_number);

CREATE INDEX properties_phase_idx ON properties(phase_id);

INSERT INTO hoa_phases (name, slug, status)
VALUES ('Existing Community', 'existing-community', 'active');

INSERT INTO properties (phase_id, street_number, street_name, street_suffix)
VALUES
  (1, 512, 'Abbey', 'Rd'),
  (1, 516, 'Abbey', 'Rd'),
  (1, 519, 'Abbey', 'Rd'),
  (1, 520, 'Abbey', 'Rd'),
  (1, 600, 'Abbey', 'Rd'),
  (1, 601, 'Abbey', 'Rd'),
  (1, 604, 'Abbey', 'Rd'),
  (1, 605, 'Abbey', 'Rd'),
  (1, 608, 'Abbey', 'Rd'),
  (1, 609, 'Abbey', 'Rd'),
  (1, 612, 'Abbey', 'Rd'),
  (1, 613, 'Abbey', 'Rd'),
  (1, 616, 'Abbey', 'Rd'),
  (1, 617, 'Abbey', 'Rd'),
  (1, 620, 'Abbey', 'Rd'),
  (1, 621, 'Abbey', 'Rd'),
  (1, 624, 'Abbey', 'Rd'),
  (1, 625, 'Abbey', 'Rd'),
  (1, 628, 'Abbey', 'Rd'),
  (1, 629, 'Abbey', 'Rd'),
  (1, 632, 'Abbey', 'Rd'),
  (1, 636, 'Abbey', 'Rd'),
  (1, 640, 'Abbey', 'Rd'),
  (1, 644, 'Abbey', 'Rd'),
  (1, 648, 'Abbey', 'Rd'),
  (1, 700, 'Abbey', 'Rd'),
  (1, 704, 'Abbey', 'Rd'),
  (1, 708, 'Abbey', 'Rd'),
  (1, 712, 'Abbey', 'Rd'),
  (1, 714, 'Abbey', 'Rd'),
  (1, 716, 'Abbey', 'Rd'),
  (1, 718, 'Abbey', 'Rd'),
  (1, 719, 'Abbey', 'Rd'),
  (1, 720, 'Abbey', 'Rd'),
  (1, 721, 'Abbey', 'Rd'),
  (1, 722, 'Abbey', 'Rd'),
  (1, 723, 'Abbey', 'Rd'),
  (1, 724, 'Abbey', 'Rd'),
  (1, 725, 'Abbey', 'Rd'),
  (1, 726, 'Abbey', 'Rd'),
  (1, 727, 'Abbey', 'Rd'),
  (1, 728, 'Abbey', 'Rd'),
  (1, 729, 'Abbey', 'Rd'),
  (1, 730, 'Abbey', 'Rd'),
  (1, 731, 'Abbey', 'Rd'),
  (1, 732, 'Abbey', 'Rd'),
  (1, 733, 'Abbey', 'Rd'),
  (1, 734, 'Abbey', 'Rd'),
  (1, 735, 'Abbey', 'Rd'),
  (1, 736, 'Abbey', 'Rd'),
  (1, 737, 'Abbey', 'Rd'),
  (1, 738, 'Abbey', 'Rd'),
  (1, 739, 'Abbey', 'Rd'),
  (1, 740, 'Abbey', 'Rd'),
  (1, 742, 'Abbey', 'Rd'),
  (1, 744, 'Abbey', 'Rd'),
  (1, 746, 'Abbey', 'Rd'),
  (1, 748, 'Abbey', 'Rd'),
  (1, 900, 'Abbey', 'Rd'),
  (1, 904, 'Abbey', 'Rd'),
  (1, 908, 'Abbey', 'Rd'),
  (1, 912, 'Abbey', 'Rd'),
  (1, 916, 'Abbey', 'Rd'),
  (1, 572, 'Imagine', 'Dr'),
  (1, 573, 'Imagine', 'Dr'),
  (1, 576, 'Imagine', 'Dr'),
  (1, 577, 'Imagine', 'Dr'),
  (1, 581, 'Imagine', 'Dr'),
  (1, 584, 'Imagine', 'Dr'),
  (1, 588, 'Imagine', 'Dr'),
  (1, 589, 'Imagine', 'Dr'),
  (1, 593, 'Imagine', 'Dr'),
  (1, 597, 'Imagine', 'Dr'),
  (1, 600, 'Imagine', 'Dr'),
  (1, 601, 'Imagine', 'Dr'),
  (1, 604, 'Imagine', 'Dr'),
  (1, 605, 'Imagine', 'Dr'),
  (1, 608, 'Imagine', 'Dr'),
  (1, 609, 'Imagine', 'Dr'),
  (1, 612, 'Imagine', 'Dr'),
  (1, 613, 'Imagine', 'Dr'),
  (1, 616, 'Imagine', 'Dr'),
  (1, 617, 'Imagine', 'Dr'),
  (1, 620, 'Imagine', 'Dr'),
  (1, 621, 'Imagine', 'Dr'),
  (1, 625, 'Imagine', 'Dr'),
  (1, 600, 'Yesterday', 'Dr'),
  (1, 601, 'Yesterday', 'Dr'),
  (1, 604, 'Yesterday', 'Dr'),
  (1, 608, 'Yesterday', 'Dr'),
  (1, 609, 'Yesterday', 'Dr'),
  (1, 612, 'Yesterday', 'Dr'),
  (1, 613, 'Yesterday', 'Dr'),
  (1, 616, 'Yesterday', 'Dr'),
  (1, 617, 'Yesterday', 'Dr'),
  (1, 620, 'Yesterday', 'Dr'),
  (1, 621, 'Yesterday', 'Dr'),
  (1, 624, 'Yesterday', 'Dr'),
  (1, 625, 'Yesterday', 'Dr'),
  (1, 628, 'Yesterday', 'Dr'),
  (1, 629, 'Yesterday', 'Dr');
